#!/bin/bash
sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install vagrant
touch Vagrantfile

$mach_quant = 3

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory=16384
      vb.cpus=8
      vb.check_guest_additions=false
  config.vm.box_check_update=true
  config.vm.box="ubuntu/focal64"
  config.disksize.size = "300GB"
 end

(1..$mach_quant).each do |i|
    config.vm.define "node#{i}" do |node|
        node.vm.network "public_network", ip: "192.168.1.#{24+i}"
        node.vm.hostname = "node#{i}"
    end
end

end
